import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import NavBar from "./components/navigation-bar";
import { AuthProvider } from "./contexts/auth-context";
import ClientWrapper from "./components/client-wrapper";
import { PostsProvider } from "./contexts/posts-context";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <PostsProvider>
        <html lang="en">
          <body className={inter.className}>
            <NavBar></NavBar>
            <ClientWrapper>{children}</ClientWrapper>
            <Toaster />
          </body>
        </html>
      </PostsProvider>
    </AuthProvider>
  );
}
